admin = "پسورد پنل بزار"
emaill = "جیمیل خود را بگزارید"
passw = "پسورد app را بگزارید"
admin_email = "admin@أدامنه خود را بگزارید مثلا test.ir"
domain = "دامنه خودتان بگزارید مثلا test.ir"
secret_key = "حروف دلخواه برای سکرت کی بنویسید"